// Code generated by protoc-gen-go. DO NOT EDIT.
// source: configuration.proto

package hotstuff

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ConfigMetadata is serialized and set as the value of ConsensusType.Metadata in
// a channel configuration when the ConsensusType.Type is set "hotstuff".
type ConfigMetadata struct {
	Consenters           []*Consenter `protobuf:"bytes,1,rep,name=consenters,proto3" json:"consenters,omitempty"`
	Options              *Options     `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ConfigMetadata) Reset()         { *m = ConfigMetadata{} }
func (m *ConfigMetadata) String() string { return proto.CompactTextString(m) }
func (*ConfigMetadata) ProtoMessage()    {}
func (*ConfigMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_415c9e57263f32ab, []int{0}
}

func (m *ConfigMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigMetadata.Unmarshal(m, b)
}
func (m *ConfigMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigMetadata.Marshal(b, m, deterministic)
}
func (m *ConfigMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigMetadata.Merge(m, src)
}
func (m *ConfigMetadata) XXX_Size() int {
	return xxx_messageInfo_ConfigMetadata.Size(m)
}
func (m *ConfigMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigMetadata proto.InternalMessageInfo

func (m *ConfigMetadata) GetConsenters() []*Consenter {
	if m != nil {
		return m.Consenters
	}
	return nil
}

func (m *ConfigMetadata) GetOptions() *Options {
	if m != nil {
		return m.Options
	}
	return nil
}

// Consenter represents a consenting node (i.e. replica).
type Consenter struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port                 uint32   `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	ClientTlsCert        []byte   `protobuf:"bytes,3,opt,name=client_tls_cert,json=clientTlsCert,proto3" json:"client_tls_cert,omitempty"`
	ServerTlsCert        []byte   `protobuf:"bytes,4,opt,name=server_tls_cert,json=serverTlsCert,proto3" json:"server_tls_cert,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Consenter) Reset()         { *m = Consenter{} }
func (m *Consenter) String() string { return proto.CompactTextString(m) }
func (*Consenter) ProtoMessage()    {}
func (*Consenter) Descriptor() ([]byte, []int) {
	return fileDescriptor_415c9e57263f32ab, []int{1}
}

func (m *Consenter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Consenter.Unmarshal(m, b)
}
func (m *Consenter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Consenter.Marshal(b, m, deterministic)
}
func (m *Consenter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consenter.Merge(m, src)
}
func (m *Consenter) XXX_Size() int {
	return xxx_messageInfo_Consenter.Size(m)
}
func (m *Consenter) XXX_DiscardUnknown() {
	xxx_messageInfo_Consenter.DiscardUnknown(m)
}

var xxx_messageInfo_Consenter proto.InternalMessageInfo

func (m *Consenter) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Consenter) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Consenter) GetClientTlsCert() []byte {
	if m != nil {
		return m.ClientTlsCert
	}
	return nil
}

func (m *Consenter) GetServerTlsCert() []byte {
	if m != nil {
		return m.ServerTlsCert
	}
	return nil
}

// Options to be specified for all the etcd/raft nodes. These can be modified on a
// per-channel basis.
type Options struct {
	TickInterval      string `protobuf:"bytes,1,opt,name=tick_interval,json=tickInterval,proto3" json:"tick_interval,omitempty"`
	ElectionTick      uint32 `protobuf:"varint,2,opt,name=election_tick,json=electionTick,proto3" json:"election_tick,omitempty"`
	HeartbeatTick     uint32 `protobuf:"varint,3,opt,name=heartbeat_tick,json=heartbeatTick,proto3" json:"heartbeat_tick,omitempty"`
	MaxInflightBlocks uint32 `protobuf:"varint,4,opt,name=max_inflight_blocks,json=maxInflightBlocks,proto3" json:"max_inflight_blocks,omitempty"`
	// Take snapshot when cumulative data exceeds certain size in bytes.
	SnapshotIntervalSize uint32   `protobuf:"varint,5,opt,name=snapshot_interval_size,json=snapshotIntervalSize,proto3" json:"snapshot_interval_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Options) Reset()         { *m = Options{} }
func (m *Options) String() string { return proto.CompactTextString(m) }
func (*Options) ProtoMessage()    {}
func (*Options) Descriptor() ([]byte, []int) {
	return fileDescriptor_415c9e57263f32ab, []int{2}
}

func (m *Options) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Options.Unmarshal(m, b)
}
func (m *Options) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Options.Marshal(b, m, deterministic)
}
func (m *Options) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Options.Merge(m, src)
}
func (m *Options) XXX_Size() int {
	return xxx_messageInfo_Options.Size(m)
}
func (m *Options) XXX_DiscardUnknown() {
	xxx_messageInfo_Options.DiscardUnknown(m)
}

var xxx_messageInfo_Options proto.InternalMessageInfo

func (m *Options) GetTickInterval() string {
	if m != nil {
		return m.TickInterval
	}
	return ""
}

func (m *Options) GetElectionTick() uint32 {
	if m != nil {
		return m.ElectionTick
	}
	return 0
}

func (m *Options) GetHeartbeatTick() uint32 {
	if m != nil {
		return m.HeartbeatTick
	}
	return 0
}

func (m *Options) GetMaxInflightBlocks() uint32 {
	if m != nil {
		return m.MaxInflightBlocks
	}
	return 0
}

func (m *Options) GetSnapshotIntervalSize() uint32 {
	if m != nil {
		return m.SnapshotIntervalSize
	}
	return 0
}

// BlockMetadata stores data used by the Raft OSNs when
// coordinating with each other, to be serialized into
// block meta dta field and used after failres and restarts.
type BlockMetadata struct {
	// Maintains a mapping between the cluster's OSNs
	// and their Raft IDs.
	ConsenterIds []uint64 `protobuf:"varint,1,rep,packed,name=consenter_ids,json=consenterIds,proto3" json:"consenter_ids,omitempty"`
	// Carries the Raft ID value that will be assigned
	// to the next OSN that will join this cluster.
	NextConsenterId uint64 `protobuf:"varint,2,opt,name=next_consenter_id,json=nextConsenterId,proto3" json:"next_consenter_id,omitempty"`
	// Index of etcd/raft entry for current block.
	RaftIndex            uint64   `protobuf:"varint,3,opt,name=raft_index,json=raftIndex,proto3" json:"raft_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockMetadata) Reset()         { *m = BlockMetadata{} }
func (m *BlockMetadata) String() string { return proto.CompactTextString(m) }
func (*BlockMetadata) ProtoMessage()    {}
func (*BlockMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_415c9e57263f32ab, []int{3}
}

func (m *BlockMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockMetadata.Unmarshal(m, b)
}
func (m *BlockMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockMetadata.Marshal(b, m, deterministic)
}
func (m *BlockMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockMetadata.Merge(m, src)
}
func (m *BlockMetadata) XXX_Size() int {
	return xxx_messageInfo_BlockMetadata.Size(m)
}
func (m *BlockMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_BlockMetadata proto.InternalMessageInfo

func (m *BlockMetadata) GetConsenterIds() []uint64 {
	if m != nil {
		return m.ConsenterIds
	}
	return nil
}

func (m *BlockMetadata) GetNextConsenterId() uint64 {
	if m != nil {
		return m.NextConsenterId
	}
	return 0
}

func (m *BlockMetadata) GetRaftIndex() uint64 {
	if m != nil {
		return m.RaftIndex
	}
	return 0
}

func init() {
	proto.RegisterType((*ConfigMetadata)(nil), "hotstuff.ConfigMetadata")
	proto.RegisterType((*Consenter)(nil), "hotstuff.Consenter")
	proto.RegisterType((*Options)(nil), "hotstuff.Options")
	proto.RegisterType((*BlockMetadata)(nil), "hotstuff.BlockMetadata")
}

func init() { proto.RegisterFile("configuration.proto", fileDescriptor_415c9e57263f32ab) }

var fileDescriptor_415c9e57263f32ab = []byte{
	// 390 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x92, 0xcf, 0x6a, 0xdc, 0x30,
	0x10, 0xc6, 0x71, 0xd7, 0x6d, 0xba, 0x93, 0x75, 0xc2, 0x6a, 0x4b, 0xf1, 0xa5, 0xb0, 0x6c, 0x68,
	0x59, 0x5a, 0xd8, 0x43, 0xd2, 0x27, 0xa8, 0x4f, 0x3e, 0x94, 0x82, 0x9a, 0xbb, 0xd0, 0xca, 0xe3,
	0x58, 0xac, 0x23, 0x19, 0x69, 0x12, 0x4c, 0x2e, 0x3d, 0xf4, 0x45, 0xfb, 0x28, 0x45, 0xf2, 0x9f,
	0xcd, 0x4d, 0xfc, 0xbe, 0xdf, 0xc8, 0x9f, 0x18, 0xc3, 0x46, 0x59, 0x53, 0xeb, 0x87, 0x27, 0x27,
	0x49, 0x5b, 0x73, 0xe8, 0x9c, 0x25, 0xcb, 0xde, 0x37, 0x96, 0x3c, 0x3d, 0xd5, 0xf5, 0xce, 0xc1,
	0x55, 0x11, 0x85, 0x9f, 0x48, 0xb2, 0x92, 0x24, 0xd9, 0x1d, 0x80, 0xb2, 0xc6, 0xa3, 0x21, 0x74,
	0x3e, 0x4f, 0xb6, 0x8b, 0xfd, 0xe5, 0xed, 0xe6, 0x30, 0x0d, 0x1c, 0x8a, 0x29, 0xe3, 0xaf, 0x34,
	0xf6, 0x0d, 0x2e, 0x6c, 0x17, 0x3e, 0xe0, 0xf3, 0x37, 0xdb, 0x64, 0x7f, 0x79, 0xbb, 0x3e, 0x4f,
	0xfc, 0x1a, 0x02, 0x3e, 0x19, 0xbb, 0xbf, 0x09, 0x2c, 0xe7, 0x6b, 0x18, 0x83, 0xb4, 0xb1, 0x9e,
	0xf2, 0x64, 0x9b, 0xec, 0x97, 0x3c, 0x9e, 0x03, 0xeb, 0xac, 0xa3, 0x78, 0x57, 0xc6, 0xe3, 0x99,
	0x7d, 0x81, 0x6b, 0xd5, 0x6a, 0x34, 0x24, 0xa8, 0xf5, 0x42, 0xa1, 0xa3, 0x7c, 0xb1, 0x4d, 0xf6,
	0x2b, 0x9e, 0x0d, 0xf8, 0xbe, 0xf5, 0x05, 0x0e, 0x9e, 0x47, 0xf7, 0x8c, 0xee, 0xec, 0xa5, 0x83,
	0x37, 0xe0, 0xd1, 0xdb, 0xfd, 0x4b, 0xe0, 0x62, 0xac, 0xc6, 0x6e, 0x20, 0x23, 0xad, 0x4e, 0x42,
	0x87, 0x46, 0xcf, 0xb2, 0x1d, 0xcb, 0xac, 0x02, 0x2c, 0x47, 0x16, 0x24, 0x6c, 0x51, 0x85, 0x09,
	0x11, 0x82, 0xb1, 0xdd, 0x6a, 0x82, 0xf7, 0x5a, 0x9d, 0xd8, 0x67, 0xb8, 0x6a, 0x50, 0x3a, 0x3a,
	0xa2, 0xa4, 0xc1, 0x5a, 0x44, 0x2b, 0x9b, 0x69, 0xd4, 0x0e, 0xb0, 0x79, 0x94, 0xbd, 0xd0, 0xa6,
	0x6e, 0xf5, 0x43, 0x43, 0xe2, 0xd8, 0x5a, 0x75, 0xf2, 0xb1, 0x68, 0xc6, 0xd7, 0x8f, 0xb2, 0x2f,
	0xc7, 0xe4, 0x47, 0x0c, 0xd8, 0x77, 0xf8, 0xe8, 0x8d, 0xec, 0x7c, 0x63, 0x69, 0x2e, 0x29, 0xbc,
	0x7e, 0xc1, 0xfc, 0x6d, 0x1c, 0xf9, 0x30, 0xa5, 0x53, 0xdb, 0xdf, 0xfa, 0x05, 0x77, 0x7f, 0x20,
	0x8b, 0xf3, 0xf3, 0x6e, 0x6f, 0x20, 0x9b, 0x97, 0x26, 0x74, 0x35, 0xac, 0x37, 0xe5, 0xab, 0x19,
	0x96, 0x95, 0x67, 0x5f, 0x61, 0x6d, 0xb0, 0x27, 0xf1, 0xda, 0x8c, 0x6f, 0x4d, 0xf9, 0x75, 0x08,
	0x8a, 0xb3, 0xcc, 0x3e, 0x01, 0x38, 0x59, 0x87, 0x4e, 0x15, 0xf6, 0xf1, 0xa9, 0x29, 0x5f, 0x06,
	0x52, 0x06, 0x70, 0x7c, 0x17, 0x7f, 0xb7, 0xbb, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x8b, 0x7d,
	0x99, 0x51, 0x85, 0x02, 0x00, 0x00,
}
