// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hotstuffmsg.proto

package hotstuff

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	// Types that are valid to be assigned to Type:
	//	*Message_Proposal
	//	*Message_Newview
	//	*Message_Vote
	//	*Message_Sync
	Type                 isMessage_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_82fdd8db94217de3, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

type isMessage_Type interface {
	isMessage_Type()
}

type Message_Proposal struct {
	Proposal *Proposal `protobuf:"bytes,1,opt,name=proposal,proto3,oneof"`
}

type Message_Newview struct {
	Newview *NewView `protobuf:"bytes,2,opt,name=newview,proto3,oneof"`
}

type Message_Vote struct {
	Vote *Vote `protobuf:"bytes,3,opt,name=vote,proto3,oneof"`
}

type Message_Sync struct {
	Sync *Sync `protobuf:"bytes,4,opt,name=sync,proto3,oneof"`
}

func (*Message_Proposal) isMessage_Type() {}

func (*Message_Newview) isMessage_Type() {}

func (*Message_Vote) isMessage_Type() {}

func (*Message_Sync) isMessage_Type() {}

func (m *Message) GetType() isMessage_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Message) GetProposal() *Proposal {
	if x, ok := m.GetType().(*Message_Proposal); ok {
		return x.Proposal
	}
	return nil
}

func (m *Message) GetNewview() *NewView {
	if x, ok := m.GetType().(*Message_Newview); ok {
		return x.Newview
	}
	return nil
}

func (m *Message) GetVote() *Vote {
	if x, ok := m.GetType().(*Message_Vote); ok {
		return x.Vote
	}
	return nil
}

func (m *Message) GetSync() *Sync {
	if x, ok := m.GetType().(*Message_Sync); ok {
		return x.Sync
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Message) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Message_Proposal)(nil),
		(*Message_Newview)(nil),
		(*Message_Vote)(nil),
		(*Message_Sync)(nil),
	}
}

type SyncRequest struct {
	From *Header `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	// zero limit sends all
	Limit                uint64   `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncRequest) Reset()         { *m = SyncRequest{} }
func (m *SyncRequest) String() string { return proto.CompactTextString(m) }
func (*SyncRequest) ProtoMessage()    {}
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82fdd8db94217de3, []int{1}
}

func (m *SyncRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncRequest.Unmarshal(m, b)
}
func (m *SyncRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncRequest.Marshal(b, m, deterministic)
}
func (m *SyncRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncRequest.Merge(m, src)
}
func (m *SyncRequest) XXX_Size() int {
	return xxx_messageInfo_SyncRequest.Size(m)
}
func (m *SyncRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SyncRequest proto.InternalMessageInfo

func (m *SyncRequest) GetFrom() *Header {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *SyncRequest) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

// Proposal carries header and data of the new proposal and certificate of the parent.
type Proposal struct {
	Header     *Header      `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data       *Data        `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Sig        []byte       `protobuf:"bytes,3,opt,name=sig,proto3" json:"sig,omitempty"`
	ParentCert *Certificate `protobuf:"bytes,4,opt,name=parentCert,proto3" json:"parentCert,omitempty"`
	// any time view change happens by timeout - there must be a timeout certificate
	// used to sync replicas on the same block
	Timeout              *TimeoutCertificate `protobuf:"bytes,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Proposal) Reset()         { *m = Proposal{} }
func (m *Proposal) String() string { return proto.CompactTextString(m) }
func (*Proposal) ProtoMessage()    {}
func (*Proposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_82fdd8db94217de3, []int{2}
}

func (m *Proposal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proposal.Unmarshal(m, b)
}
func (m *Proposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proposal.Marshal(b, m, deterministic)
}
func (m *Proposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proposal.Merge(m, src)
}
func (m *Proposal) XXX_Size() int {
	return xxx_messageInfo_Proposal.Size(m)
}
func (m *Proposal) XXX_DiscardUnknown() {
	xxx_messageInfo_Proposal.DiscardUnknown(m)
}

var xxx_messageInfo_Proposal proto.InternalMessageInfo

func (m *Proposal) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Proposal) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Proposal) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *Proposal) GetParentCert() *Certificate {
	if m != nil {
		return m.ParentCert
	}
	return nil
}

func (m *Proposal) GetTimeout() *TimeoutCertificate {
	if m != nil {
		return m.Timeout
	}
	return nil
}

type NewView struct {
	View                 uint64       `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Voter                uint64       `protobuf:"varint,2,opt,name=voter,proto3" json:"voter,omitempty"`
	Sig                  []byte       `protobuf:"bytes,3,opt,name=sig,proto3" json:"sig,omitempty"`
	Cert                 *Certificate `protobuf:"bytes,4,opt,name=cert,proto3" json:"cert,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *NewView) Reset()         { *m = NewView{} }
func (m *NewView) String() string { return proto.CompactTextString(m) }
func (*NewView) ProtoMessage()    {}
func (*NewView) Descriptor() ([]byte, []int) {
	return fileDescriptor_82fdd8db94217de3, []int{3}
}

func (m *NewView) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewView.Unmarshal(m, b)
}
func (m *NewView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewView.Marshal(b, m, deterministic)
}
func (m *NewView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewView.Merge(m, src)
}
func (m *NewView) XXX_Size() int {
	return xxx_messageInfo_NewView.Size(m)
}
func (m *NewView) XXX_DiscardUnknown() {
	xxx_messageInfo_NewView.DiscardUnknown(m)
}

var xxx_messageInfo_NewView proto.InternalMessageInfo

func (m *NewView) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *NewView) GetVoter() uint64 {
	if m != nil {
		return m.Voter
	}
	return 0
}

func (m *NewView) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *NewView) GetCert() *Certificate {
	if m != nil {
		return m.Cert
	}
	return nil
}

// Block will be used mostly for synchronization of the replicas that lag behind.
type Block struct {
	Header               *Header      `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data                 *Data        `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Cert                 *Certificate `protobuf:"bytes,3,opt,name=cert,proto3" json:"cert,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_82fdd8db94217de3, []int{4}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Block) GetCert() *Certificate {
	if m != nil {
		return m.Cert
	}
	return nil
}

type Header struct {
	View                 uint64   `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Parent               []byte   `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	ParentView           uint64   `protobuf:"varint,3,opt,name=parentView,proto3" json:"parentView,omitempty"`
	DataRoot             []byte   `protobuf:"bytes,4,opt,name=dataRoot,proto3" json:"dataRoot,omitempty"`
	StateRoot            []byte   `protobuf:"bytes,5,opt,name=stateRoot,proto3" json:"stateRoot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_82fdd8db94217de3, []int{5}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *Header) GetParent() []byte {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *Header) GetParentView() uint64 {
	if m != nil {
		return m.ParentView
	}
	return 0
}

func (m *Header) GetDataRoot() []byte {
	if m != nil {
		return m.DataRoot
	}
	return nil
}

func (m *Header) GetStateRoot() []byte {
	if m != nil {
		return m.StateRoot
	}
	return nil
}

// Vote should be naturally aggregated into the certificate.
type Vote struct {
	Block                []byte   `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	View                 uint64   `protobuf:"varint,2,opt,name=view,proto3" json:"view,omitempty"`
	Voter                uint64   `protobuf:"varint,3,opt,name=voter,proto3" json:"voter,omitempty"`
	Sig                  []byte   `protobuf:"bytes,4,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vote) Reset()         { *m = Vote{} }
func (m *Vote) String() string { return proto.CompactTextString(m) }
func (*Vote) ProtoMessage()    {}
func (*Vote) Descriptor() ([]byte, []int) {
	return fileDescriptor_82fdd8db94217de3, []int{6}
}

func (m *Vote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vote.Unmarshal(m, b)
}
func (m *Vote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vote.Marshal(b, m, deterministic)
}
func (m *Vote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vote.Merge(m, src)
}
func (m *Vote) XXX_Size() int {
	return xxx_messageInfo_Vote.Size(m)
}
func (m *Vote) XXX_DiscardUnknown() {
	xxx_messageInfo_Vote.DiscardUnknown(m)
}

var xxx_messageInfo_Vote proto.InternalMessageInfo

func (m *Vote) GetBlock() []byte {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *Vote) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *Vote) GetVoter() uint64 {
	if m != nil {
		return m.Voter
	}
	return 0
}

func (m *Vote) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

type Certificate struct {
	Block                []byte               `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	Sig                  *AggregatedSignature `protobuf:"bytes,2,opt,name=Sig,json=sig,proto3" json:"Sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Certificate) Reset()         { *m = Certificate{} }
func (m *Certificate) String() string { return proto.CompactTextString(m) }
func (*Certificate) ProtoMessage()    {}
func (*Certificate) Descriptor() ([]byte, []int) {
	return fileDescriptor_82fdd8db94217de3, []int{7}
}

func (m *Certificate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Certificate.Unmarshal(m, b)
}
func (m *Certificate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Certificate.Marshal(b, m, deterministic)
}
func (m *Certificate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Certificate.Merge(m, src)
}
func (m *Certificate) XXX_Size() int {
	return xxx_messageInfo_Certificate.Size(m)
}
func (m *Certificate) XXX_DiscardUnknown() {
	xxx_messageInfo_Certificate.DiscardUnknown(m)
}

var xxx_messageInfo_Certificate proto.InternalMessageInfo

func (m *Certificate) GetBlock() []byte {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *Certificate) GetSig() *AggregatedSignature {
	if m != nil {
		return m.Sig
	}
	return nil
}

type TimeoutCertificate struct {
	View                 uint64               `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Sig                  *AggregatedSignature `protobuf:"bytes,2,opt,name=Sig,json=sig,proto3" json:"Sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TimeoutCertificate) Reset()         { *m = TimeoutCertificate{} }
func (m *TimeoutCertificate) String() string { return proto.CompactTextString(m) }
func (*TimeoutCertificate) ProtoMessage()    {}
func (*TimeoutCertificate) Descriptor() ([]byte, []int) {
	return fileDescriptor_82fdd8db94217de3, []int{8}
}

func (m *TimeoutCertificate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeoutCertificate.Unmarshal(m, b)
}
func (m *TimeoutCertificate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeoutCertificate.Marshal(b, m, deterministic)
}
func (m *TimeoutCertificate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeoutCertificate.Merge(m, src)
}
func (m *TimeoutCertificate) XXX_Size() int {
	return xxx_messageInfo_TimeoutCertificate.Size(m)
}
func (m *TimeoutCertificate) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeoutCertificate.DiscardUnknown(m)
}

var xxx_messageInfo_TimeoutCertificate proto.InternalMessageInfo

func (m *TimeoutCertificate) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *TimeoutCertificate) GetSig() *AggregatedSignature {
	if m != nil {
		return m.Sig
	}
	return nil
}

type AggregatedSignature struct {
	Voters               []uint64 `protobuf:"varint,1,rep,packed,name=voters,proto3" json:"voters,omitempty"`
	Sig                  []byte   `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AggregatedSignature) Reset()         { *m = AggregatedSignature{} }
func (m *AggregatedSignature) String() string { return proto.CompactTextString(m) }
func (*AggregatedSignature) ProtoMessage()    {}
func (*AggregatedSignature) Descriptor() ([]byte, []int) {
	return fileDescriptor_82fdd8db94217de3, []int{9}
}

func (m *AggregatedSignature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AggregatedSignature.Unmarshal(m, b)
}
func (m *AggregatedSignature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AggregatedSignature.Marshal(b, m, deterministic)
}
func (m *AggregatedSignature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AggregatedSignature.Merge(m, src)
}
func (m *AggregatedSignature) XXX_Size() int {
	return xxx_messageInfo_AggregatedSignature.Size(m)
}
func (m *AggregatedSignature) XXX_DiscardUnknown() {
	xxx_messageInfo_AggregatedSignature.DiscardUnknown(m)
}

var xxx_messageInfo_AggregatedSignature proto.InternalMessageInfo

func (m *AggregatedSignature) GetVoters() []uint64 {
	if m != nil {
		return m.Voters
	}
	return nil
}

func (m *AggregatedSignature) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

type Data struct {
	Data                 []*Transaction `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_82fdd8db94217de3, []int{10}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetData() []*Transaction {
	if m != nil {
		return m.Data
	}
	return nil
}

type Transaction struct {
	Account              []byte   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Nonce                uint64   `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Sig                  []byte   `protobuf:"bytes,4,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_82fdd8db94217de3, []int{11}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetAccount() []byte {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *Transaction) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Transaction) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Transaction) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

type Sync struct {
	Blocks               []*Block `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sync) Reset()         { *m = Sync{} }
func (m *Sync) String() string { return proto.CompactTextString(m) }
func (*Sync) ProtoMessage()    {}
func (*Sync) Descriptor() ([]byte, []int) {
	return fileDescriptor_82fdd8db94217de3, []int{12}
}

func (m *Sync) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sync.Unmarshal(m, b)
}
func (m *Sync) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sync.Marshal(b, m, deterministic)
}
func (m *Sync) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sync.Merge(m, src)
}
func (m *Sync) XXX_Size() int {
	return xxx_messageInfo_Sync.Size(m)
}
func (m *Sync) XXX_DiscardUnknown() {
	xxx_messageInfo_Sync.DiscardUnknown(m)
}

var xxx_messageInfo_Sync proto.InternalMessageInfo

func (m *Sync) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "hotstuff.Message")
	proto.RegisterType((*SyncRequest)(nil), "hotstuff.SyncRequest")
	proto.RegisterType((*Proposal)(nil), "hotstuff.Proposal")
	proto.RegisterType((*NewView)(nil), "hotstuff.NewView")
	proto.RegisterType((*Block)(nil), "hotstuff.Block")
	proto.RegisterType((*Header)(nil), "hotstuff.Header")
	proto.RegisterType((*Vote)(nil), "hotstuff.Vote")
	proto.RegisterType((*Certificate)(nil), "hotstuff.Certificate")
	proto.RegisterType((*TimeoutCertificate)(nil), "hotstuff.TimeoutCertificate")
	proto.RegisterType((*AggregatedSignature)(nil), "hotstuff.AggregatedSignature")
	proto.RegisterType((*Data)(nil), "hotstuff.Data")
	proto.RegisterType((*Transaction)(nil), "hotstuff.Transaction")
	proto.RegisterType((*Sync)(nil), "hotstuff.Sync")
}

func init() { proto.RegisterFile("hotstuffmsg.proto", fileDescriptor_82fdd8db94217de3) }

var fileDescriptor_82fdd8db94217de3 = []byte{
	// 594 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0x5e, 0x16, 0x37, 0x2d, 0xa7, 0x15, 0x6c, 0xe6, 0x47, 0x11, 0x1a, 0x68, 0x8a, 0x90, 0x28,
	0x17, 0x74, 0xfc, 0x08, 0x6e, 0x11, 0x63, 0x17, 0xe5, 0x02, 0x84, 0xdc, 0x6a, 0x82, 0x4b, 0x2f,
	0x75, 0x33, 0x8b, 0x36, 0x0e, 0xb1, 0xbb, 0xaa, 0x77, 0x3c, 0x01, 0x8f, 0xc4, 0x7b, 0xf0, 0x36,
	0xc8, 0x27, 0x76, 0x93, 0x41, 0xa6, 0x09, 0x89, 0xbb, 0x9c, 0xf3, 0x7d, 0xc7, 0xfe, 0xce, 0x77,
	0x8e, 0x03, 0xfb, 0xe7, 0xca, 0x68, 0xb3, 0x9a, 0xcf, 0x97, 0x3a, 0x1b, 0x15, 0xa5, 0x32, 0x8a,
	0xf6, 0x7c, 0x2a, 0xf9, 0x19, 0x40, 0xf7, 0x83, 0xd0, 0x9a, 0x67, 0x82, 0x3e, 0x83, 0x5e, 0x51,
	0xaa, 0x42, 0x69, 0xbe, 0x88, 0x83, 0xc3, 0x60, 0xd8, 0x7f, 0x41, 0x47, 0x9e, 0x38, 0xfa, 0xe4,
	0x90, 0xf1, 0x0e, 0xdb, 0xb2, 0xe8, 0x53, 0xe8, 0xe6, 0x62, 0x7d, 0x21, 0xc5, 0x3a, 0xde, 0xc5,
	0x82, 0xfd, 0xba, 0xe0, 0xa3, 0x58, 0x9f, 0x4a, 0xb1, 0x1e, 0xef, 0x30, 0xcf, 0xa1, 0x8f, 0x80,
	0x5c, 0x28, 0x23, 0xe2, 0x10, 0xb9, 0x37, 0x6b, 0xee, 0xa9, 0x32, 0x62, 0xbc, 0xc3, 0x10, 0xb5,
	0x2c, 0xbd, 0xc9, 0xd3, 0x98, 0xfc, 0xc9, 0x9a, 0x6c, 0xf2, 0xd4, 0xb2, 0x2c, 0x7a, 0x1c, 0x01,
	0x31, 0x9b, 0x42, 0x24, 0xef, 0xa1, 0x6f, 0xf3, 0x4c, 0x7c, 0x5b, 0x09, 0x6d, 0x6c, 0xf1, 0xbc,
	0x54, 0x4b, 0xa7, 0x7f, 0xaf, 0x2e, 0x1e, 0x0b, 0x3e, 0x13, 0x25, 0x43, 0x94, 0xde, 0x81, 0xce,
	0x42, 0x2e, 0xa5, 0x41, 0xd5, 0x84, 0x55, 0x41, 0xf2, 0x2b, 0x80, 0x9e, 0x6f, 0x93, 0x0e, 0x21,
	0x3a, 0xc7, 0x92, 0x2b, 0x8f, 0x72, 0x38, 0x4d, 0x80, 0xcc, 0xb8, 0xe1, 0xce, 0x81, 0x86, 0xde,
	0x13, 0x6e, 0x38, 0x43, 0x8c, 0xee, 0x41, 0xa8, 0x65, 0x86, 0x8d, 0x0f, 0x98, 0xfd, 0xa4, 0xaf,
	0x00, 0x0a, 0x5e, 0x8a, 0xdc, 0xbc, 0x13, 0xa5, 0x71, 0xbd, 0xde, 0xad, 0x6b, 0x6d, 0x56, 0xce,
	0x65, 0xca, 0x8d, 0x60, 0x0d, 0x22, 0x7d, 0x0d, 0x5d, 0x23, 0x97, 0x42, 0xad, 0x4c, 0xdc, 0xc1,
	0x9a, 0x83, 0xba, 0x66, 0x5a, 0x01, 0xcd, 0x52, 0x4f, 0x4e, 0x0a, 0xe8, 0xba, 0x81, 0x50, 0x0a,
	0x04, 0x27, 0x16, 0x60, 0xef, 0xf8, 0x6d, 0x0d, 0xb1, 0xde, 0x97, 0xde, 0x10, 0x0c, 0x5a, 0x54,
	0x3f, 0x01, 0x92, 0x5e, 0xab, 0x17, 0x29, 0xc9, 0xf7, 0x00, 0x3a, 0xc7, 0x0b, 0x95, 0x7e, 0xfd,
	0xcf, 0x56, 0x7a, 0x09, 0xe1, 0xf5, 0x12, 0x7e, 0x04, 0x10, 0x55, 0x37, 0xb4, 0x36, 0x7d, 0x0f,
	0xa2, 0xca, 0x59, 0xbc, 0x6f, 0xc0, 0x5c, 0x44, 0x1f, 0xfa, 0xd1, 0x58, 0xbb, 0xf0, 0x1e, 0xc2,
	0x1a, 0x19, 0x7a, 0x1f, 0x7a, 0x56, 0x09, 0x53, 0xaa, 0x32, 0x62, 0xc0, 0xb6, 0x31, 0x3d, 0x80,
	0x1b, 0xda, 0x58, 0x05, 0x16, 0xec, 0x20, 0x58, 0x27, 0x92, 0xcf, 0x40, 0xec, 0xaa, 0x5b, 0xbb,
	0xcf, 0xac, 0x35, 0x28, 0x67, 0xc0, 0xaa, 0x60, 0xab, 0x71, 0xb7, 0x6d, 0x30, 0x61, 0xcb, 0x60,
	0xc8, 0x76, 0x30, 0xc9, 0x14, 0xfa, 0x8d, 0xfe, 0xaf, 0xb8, 0xe0, 0x08, 0xc2, 0x89, 0xcc, 0x9c,
	0xbb, 0x0f, 0x6a, 0xe7, 0xde, 0x66, 0x59, 0x29, 0x32, 0x6e, 0xc4, 0x6c, 0x22, 0xb3, 0x9c, 0x9b,
	0x55, 0x29, 0xaa, 0x53, 0xbf, 0x00, 0xfd, 0x7b, 0xa9, 0x5a, 0xbd, 0xfc, 0xe7, 0xa3, 0xdf, 0xc0,
	0xed, 0x16, 0xcc, 0xce, 0x04, 0x5b, 0xd4, 0x71, 0x70, 0x18, 0x0e, 0x09, 0x73, 0x91, 0xef, 0x78,
	0xb7, 0xee, 0xf8, 0x39, 0x90, 0x13, 0xb7, 0x0f, 0xb8, 0x33, 0x96, 0x7f, 0x69, 0x1f, 0xa6, 0x25,
	0xcf, 0x35, 0x4f, 0x8d, 0x54, 0x79, 0xb5, 0x3a, 0x49, 0x0a, 0xfd, 0x46, 0x92, 0xc6, 0xd0, 0xe5,
	0x69, 0xaa, 0x56, 0xb9, 0x71, 0x36, 0xf9, 0xd0, 0xda, 0x97, 0xab, 0x3c, 0x15, 0xfe, 0x39, 0x60,
	0x60, 0xfb, 0xc6, 0x9b, 0xaa, 0xf7, 0x70, 0xe9, 0x61, 0x37, 0x26, 0x71, 0x04, 0xc4, 0xfe, 0x90,
	0xe8, 0x63, 0x88, 0xd0, 0x75, 0xed, 0x94, 0xdd, 0xaa, 0x95, 0xe1, 0xb3, 0x60, 0x0e, 0x3e, 0x8b,
	0xf0, 0x9f, 0xfc, 0xf2, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x70, 0x9b, 0x9e, 0xd8, 0xa8, 0x05,
	0x00, 0x00,
}
