// Code generated by protoc-gen-go. DO NOT EDIT.
// source: distribute_list.proto

package list_puller

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DistributeList struct {
	Algorithm            string            `protobuf:"bytes,1,opt,name=Algorithm,proto3" json:"Algorithm,omitempty"`
	ChannelId            string            `protobuf:"bytes,2,opt,name=ChannelId,proto3" json:"ChannelId,omitempty"`
	FileSuffix           string            `protobuf:"bytes,3,opt,name=FileSuffix,proto3" json:"FileSuffix,omitempty"`
	ParShards            int32             `protobuf:"varint,4,opt,name=ParShards,proto3" json:"ParShards,omitempty"`
	DataShards           int32             `protobuf:"varint,5,opt,name=DataShards,proto3" json:"DataShards,omitempty"`
	Item                 map[string]string `protobuf:"bytes,6,rep,name=Item,proto3" json:"Item,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DistributeList) Reset()         { *m = DistributeList{} }
func (m *DistributeList) String() string { return proto.CompactTextString(m) }
func (*DistributeList) ProtoMessage()    {}
func (*DistributeList) Descriptor() ([]byte, []int) {
	return fileDescriptor_distribute_list_1f6ab448ed5d3240, []int{0}
}
func (m *DistributeList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DistributeList.Unmarshal(m, b)
}
func (m *DistributeList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DistributeList.Marshal(b, m, deterministic)
}
func (dst *DistributeList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistributeList.Merge(dst, src)
}
func (m *DistributeList) XXX_Size() int {
	return xxx_messageInfo_DistributeList.Size(m)
}
func (m *DistributeList) XXX_DiscardUnknown() {
	xxx_messageInfo_DistributeList.DiscardUnknown(m)
}

var xxx_messageInfo_DistributeList proto.InternalMessageInfo

func (m *DistributeList) GetAlgorithm() string {
	if m != nil {
		return m.Algorithm
	}
	return ""
}

func (m *DistributeList) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *DistributeList) GetFileSuffix() string {
	if m != nil {
		return m.FileSuffix
	}
	return ""
}

func (m *DistributeList) GetParShards() int32 {
	if m != nil {
		return m.ParShards
	}
	return 0
}

func (m *DistributeList) GetDataShards() int32 {
	if m != nil {
		return m.DataShards
	}
	return 0
}

func (m *DistributeList) GetItem() map[string]string {
	if m != nil {
		return m.Item
	}
	return nil
}

func init() {
	proto.RegisterType((*DistributeList)(nil), "list_puller.DistributeList")
	proto.RegisterMapType((map[string]string)(nil), "list_puller.DistributeList.ItemEntry")
}

func init() {
	proto.RegisterFile("distribute_list.proto", fileDescriptor_distribute_list_1f6ab448ed5d3240)
}

var fileDescriptor_distribute_list_1f6ab448ed5d3240 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4d, 0xc9, 0x2c, 0x2e,
	0x29, 0xca, 0x4c, 0x2a, 0x2d, 0x49, 0x8d, 0xcf, 0xc9, 0x2c, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0xe2, 0x06, 0xb1, 0xe3, 0x0b, 0x4a, 0x73, 0x72, 0x52, 0x8b, 0x94, 0xe6, 0x31, 0x71,
	0xf1, 0xb9, 0xc0, 0x95, 0xf9, 0x64, 0x16, 0x97, 0x08, 0xc9, 0x70, 0x71, 0x3a, 0xe6, 0xa4, 0xe7,
	0x17, 0x65, 0x96, 0x64, 0xe4, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x21, 0x04, 0x40, 0xb2,
	0xce, 0x19, 0x89, 0x79, 0x79, 0xa9, 0x39, 0x9e, 0x29, 0x12, 0x4c, 0x10, 0x59, 0xb8, 0x80, 0x90,
	0x1c, 0x17, 0x97, 0x5b, 0x66, 0x4e, 0x6a, 0x70, 0x69, 0x5a, 0x5a, 0x66, 0x85, 0x04, 0x33, 0x58,
	0x1a, 0x49, 0x04, 0xa4, 0x3b, 0x20, 0xb1, 0x28, 0x38, 0x23, 0xb1, 0x28, 0xa5, 0x58, 0x82, 0x45,
	0x81, 0x51, 0x83, 0x35, 0x08, 0x21, 0x00, 0xd2, 0xed, 0x92, 0x58, 0x92, 0x08, 0x95, 0x66, 0x05,
	0x4b, 0x23, 0x89, 0x08, 0x59, 0x72, 0xb1, 0x78, 0x96, 0xa4, 0xe6, 0x4a, 0xb0, 0x29, 0x30, 0x6b,
	0x70, 0x1b, 0xa9, 0xea, 0x21, 0x79, 0x44, 0x0f, 0xd5, 0x13, 0x7a, 0x20, 0x75, 0xae, 0x79, 0x25,
	0x45, 0x95, 0x41, 0x60, 0x2d, 0x52, 0xe6, 0x5c, 0x9c, 0x70, 0x21, 0x21, 0x01, 0x2e, 0xe6, 0xec,
	0xd4, 0x4a, 0xa8, 0xdf, 0x40, 0x4c, 0x21, 0x11, 0x2e, 0xd6, 0xb2, 0xc4, 0x9c, 0xd2, 0x54, 0xa8,
	0x8f, 0x20, 0x1c, 0x2b, 0x26, 0x0b, 0xc6, 0x24, 0x36, 0x70, 0xa0, 0x19, 0x03, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x65, 0x85, 0x71, 0xd4, 0x4d, 0x01, 0x00, 0x00,
}
