// Code generated by protoc-gen-go. DO NOT EDIT.
// source: distribute_list.proto

package list_puller

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LocationInfo struct {
	OrgName              string   `protobuf:"bytes,1,opt,name=OrgName,proto3" json:"OrgName,omitempty"`
	AnchorPeers          []byte   `protobuf:"bytes,2,opt,name=AnchorPeers,proto3" json:"AnchorPeers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LocationInfo) Reset()         { *m = LocationInfo{} }
func (m *LocationInfo) String() string { return proto.CompactTextString(m) }
func (*LocationInfo) ProtoMessage()    {}
func (*LocationInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_distribute_list_d9596b2afccf6460, []int{0}
}
func (m *LocationInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocationInfo.Unmarshal(m, b)
}
func (m *LocationInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocationInfo.Marshal(b, m, deterministic)
}
func (dst *LocationInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocationInfo.Merge(dst, src)
}
func (m *LocationInfo) XXX_Size() int {
	return xxx_messageInfo_LocationInfo.Size(m)
}
func (m *LocationInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LocationInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LocationInfo proto.InternalMessageInfo

func (m *LocationInfo) GetOrgName() string {
	if m != nil {
		return m.OrgName
	}
	return ""
}

func (m *LocationInfo) GetAnchorPeers() []byte {
	if m != nil {
		return m.AnchorPeers
	}
	return nil
}

type DistributeList struct {
	Algorithm            string                   `protobuf:"bytes,1,opt,name=Algorithm,proto3" json:"Algorithm,omitempty"`
	ChannelId            string                   `protobuf:"bytes,2,opt,name=ChannelId,proto3" json:"ChannelId,omitempty"`
	FileSuffix           string                   `protobuf:"bytes,3,opt,name=FileSuffix,proto3" json:"FileSuffix,omitempty"`
	ParShards            int32                    `protobuf:"varint,4,opt,name=ParShards,proto3" json:"ParShards,omitempty"`
	DataShards           int32                    `protobuf:"varint,5,opt,name=DataShards,proto3" json:"DataShards,omitempty"`
	Item                 map[string]*LocationInfo `protobuf:"bytes,6,rep,name=Item,proto3" json:"Item,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *DistributeList) Reset()         { *m = DistributeList{} }
func (m *DistributeList) String() string { return proto.CompactTextString(m) }
func (*DistributeList) ProtoMessage()    {}
func (*DistributeList) Descriptor() ([]byte, []int) {
	return fileDescriptor_distribute_list_d9596b2afccf6460, []int{1}
}
func (m *DistributeList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DistributeList.Unmarshal(m, b)
}
func (m *DistributeList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DistributeList.Marshal(b, m, deterministic)
}
func (dst *DistributeList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistributeList.Merge(dst, src)
}
func (m *DistributeList) XXX_Size() int {
	return xxx_messageInfo_DistributeList.Size(m)
}
func (m *DistributeList) XXX_DiscardUnknown() {
	xxx_messageInfo_DistributeList.DiscardUnknown(m)
}

var xxx_messageInfo_DistributeList proto.InternalMessageInfo

func (m *DistributeList) GetAlgorithm() string {
	if m != nil {
		return m.Algorithm
	}
	return ""
}

func (m *DistributeList) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *DistributeList) GetFileSuffix() string {
	if m != nil {
		return m.FileSuffix
	}
	return ""
}

func (m *DistributeList) GetParShards() int32 {
	if m != nil {
		return m.ParShards
	}
	return 0
}

func (m *DistributeList) GetDataShards() int32 {
	if m != nil {
		return m.DataShards
	}
	return 0
}

func (m *DistributeList) GetItem() map[string]*LocationInfo {
	if m != nil {
		return m.Item
	}
	return nil
}

func init() {
	proto.RegisterType((*LocationInfo)(nil), "list_puller.LocationInfo")
	proto.RegisterType((*DistributeList)(nil), "list_puller.DistributeList")
	proto.RegisterMapType((map[string]*LocationInfo)(nil), "list_puller.DistributeList.ItemEntry")
}

func init() {
	proto.RegisterFile("distribute_list.proto", fileDescriptor_distribute_list_d9596b2afccf6460)
}

var fileDescriptor_distribute_list_d9596b2afccf6460 = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0x51, 0x4b, 0xfb, 0x30,
	0x14, 0xc5, 0xe9, 0xba, 0xee, 0x4f, 0x6f, 0xc7, 0x1f, 0x09, 0x08, 0x51, 0x44, 0xca, 0x40, 0xe8,
	0x53, 0x85, 0xf9, 0xa2, 0xbe, 0x0d, 0xa7, 0x50, 0x19, 0x3a, 0xb2, 0x0f, 0x30, 0xb2, 0x35, 0x5d,
	0x83, 0x69, 0x32, 0xd2, 0x54, 0xdc, 0x47, 0xf3, 0xdb, 0x49, 0x62, 0x5d, 0xbb, 0xb7, 0xdb, 0xdf,
	0xb9, 0xe7, 0x94, 0x73, 0x03, 0xe7, 0x39, 0xaf, 0x8d, 0xe6, 0x9b, 0xc6, 0xb0, 0xb5, 0xe0, 0xb5,
	0x49, 0xf7, 0x5a, 0x19, 0x85, 0x22, 0x3b, 0xaf, 0xf7, 0x8d, 0x10, 0x4c, 0x4f, 0x5e, 0x61, 0xbc,
	0x50, 0x5b, 0x6a, 0xb8, 0x92, 0x99, 0x2c, 0x14, 0xc2, 0xf0, 0xef, 0x5d, 0xef, 0xde, 0x68, 0xc5,
	0xb0, 0x17, 0x7b, 0x49, 0x48, 0xfe, 0x3e, 0x51, 0x0c, 0xd1, 0x4c, 0x6e, 0x4b, 0xa5, 0x97, 0x8c,
	0xe9, 0x1a, 0x0f, 0x62, 0x2f, 0x19, 0x93, 0x3e, 0x9a, 0x7c, 0x0f, 0xe0, 0xff, 0xfc, 0xf8, 0xcb,
	0x05, 0xaf, 0x0d, 0xba, 0x82, 0x70, 0x26, 0x76, 0x4a, 0x73, 0x53, 0x56, 0x6d, 0x60, 0x07, 0xac,
	0xfa, 0x54, 0x52, 0x29, 0x99, 0xc8, 0x72, 0x17, 0x18, 0x92, 0x0e, 0xa0, 0x6b, 0x80, 0x17, 0x2e,
	0xd8, 0xaa, 0x29, 0x0a, 0xfe, 0x85, 0x7d, 0x27, 0xf7, 0x88, 0x75, 0x2f, 0xa9, 0x5e, 0x95, 0x54,
	0xe7, 0x35, 0x1e, 0xc6, 0x5e, 0x12, 0x90, 0x0e, 0x58, 0xf7, 0x9c, 0x1a, 0xda, 0xca, 0x81, 0x93,
	0x7b, 0x04, 0x3d, 0xc0, 0x30, 0x33, 0xac, 0xc2, 0xa3, 0xd8, 0x4f, 0xa2, 0xe9, 0x4d, 0xda, 0x3b,
	0x4a, 0x7a, 0x5a, 0x22, 0xb5, 0x7b, 0xcf, 0xd2, 0xe8, 0x03, 0x71, 0x96, 0x4b, 0x02, 0xe1, 0x11,
	0xa1, 0x33, 0xf0, 0x3f, 0xd8, 0xa1, 0xed, 0x66, 0x47, 0x74, 0x0b, 0xc1, 0x27, 0x15, 0x0d, 0x73,
	0x8d, 0xa2, 0xe9, 0xc5, 0x49, 0x74, 0xff, 0xd8, 0xe4, 0x77, 0xef, 0x71, 0x70, 0xef, 0x6d, 0x46,
	0xee, 0x6d, 0xee, 0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa3, 0xfe, 0x53, 0x4e, 0xb4, 0x01, 0x00,
	0x00,
}
